### ISSUE TITLE
Refactoring spec persister's and builder's usages

### ISSUE THREAD

**Issue by slemrmartin** [ManageIQ/inventory_refresh#25]
Removing ManageIQ's persister and builder

- [x] https://github.com/ManageIQ/inventory_refresh/pull/26 (move them to spec/helpers)
  - [x] https://github.com/ManageIQ/inventory_refresh/pull/27
    - [x] #29

**Comment by slemrmartin** [comment]
@agrare In this issue I wanted to remove all persisters and builders based on ManageIQ namespace.
I cut PRs to smaller pieces to make reviews easier

**Comment by agrare** [comment]
> I cut PRs to smaller pieces to make reviews easier

That is appreciated :)
